### ISSUE TITLE
您好 为什么选择不了答题领域呢？

### ISSUE THREAD

**Issue by L0snight** [wechat-wxapp/wechat-weapp-Game-TNFB#10]
大佬您好 ，我刚开始学微信小程序开发 然后也想写一个答题类的 ，然后看您这个，我想试一试。但排位赛的时候无法选择答题领域是什么原因？它只有一个，“选择您擅长的领域开始答题吧 ”。这一句话， 下面是空白的，  请问这是为什么呢，希望您有空可以回答一下。谢谢！！

**Comment by jacksplwxy** [comment]
答题领域也是从数据库中调取到的，请将server/tools/cAuth.sql导入到数据库
