### ISSUE TITLE
请教！急~谢谢回复~

### ISSUE THREAD

**Issue by usetme** [wechat-wxapp/wechat-weapp-Game-TNFB#11]
你好！我尝试用您的项目发布小程序测试版本（ps:不发布，只是自己想了解这个流程），基本已经配好，sql也是通的，现在问题就是不管随机匹配还是发送给好友都是连不上人，websocket也是连接成功的，请问是什么原因？

**Comment by jacksplwxy** [comment]
loopMatch 是定义的匹配函数，你可以将相关的数据打印出来，看看哪里错了

**Comment by usetme** [comment]
controllers里面的tunnel.js好像没有引用到，输出不到内容，请问是不是还有什么需要下载的或者代码需要加的？kna我也下载了

**Comment by usetme** [comment]
又试了一下，好像也是引入的，不知道从什么方向去排除了？现在就是随机匹配不到人，发送给好友也连不上
