### ISSUE TITLE
还是关于匹配的问题

### ISSUE THREAD

**Issue by usetme** [wechat-wxapp/wechat-weapp-Game-TNFB#12]
您好！现在就是匹配不到人，转发给好友也匹配不到人，不报错，也都是通的，您能给我一些建议，可能是哪里出了问题吗？非常感谢！已star

**Comment by usetme** [comment]
我现在wafer上还没有部署，用的是开发环境测试版本，会不会有影响

**Comment by jacksplwxy** [comment]
你是用的最新版吗？最新版有个错误：server/controllers/tunnel.js下的第23行，this应该要改为match；第38行的this应该去掉。之前我改了自己也没测试，就草率提交了。现在我测试了应该是可以了。你用开发环境是没问题的，我建议你查看单步调试的打印错误应该很快可以定位问题。 另外，不建议你将这个wafer方案用作正式项目： [问题传送门](https://github.com/tencentyun/wafer2-startup/issues/98)，信道有一定概率断掉。另外，这个方案也不是纯粹的客户端与服务器端websocket通信，而是前后端传送每次都要通过信道服务器作为中介者，延迟感觉也挺久的。当然我对websocket也不是太了解，这个项目仅仅是我用来学习练手的
