### ISSUE TITLE
经过测试发现了如下一些问题

### ISSUE THREAD

**Issue by vanceeasleaf** [wechat-wxapp/wechat-weapp-Game-TNFB#13]
- 用户匹配无法实现
      这是因为sortId没有正确传递到服务器上，且ws向服务器发出的信息为matchInfo,但客户端监听的是has_matched
- 答题页面无法正确显示选中的item
     这是因为js中用的是驼峰命名，而模板页中用的是下划线命名
- 给出的sql文件没有fight_record表
     因此无法记录得分信息

**Comment by jacksplwxy** [comment]
是的，没想到您看得这么仔细。之前更新了后端代码，前端漏了更新，导致很多问题给大家带来困惑。现在最新版前、后端都进行了一定的修改，应该没那么多问题了
