### ISSUE TITLE
数据库查题目的时候有时出现空数据返回

### ISSUE THREAD

**Issue by Miverk** [wechat-wxapp/wechat-weapp-Game-TNFB#16]
mysql('question_detail').where((players[openId1].sortId == 1) ? {} : { sort_id: players[openId1].sortId }).select('*').orderByRaw('RAND()').limit(option.QUESTION_NUMBER).then(res => {}

偶现查不到题目，请问是不是sdk问题 还是我那些东西没有关导致的

**Comment by jacksplwxy** [comment]
数据库查询是一个异步操作，您可以在查询语句前加await或者回调函数里打印出来查询结果。
wafer2默认数据库操作工具是[knex.js](http://knexjs.org)
