### ISSUE TITLE
无法配对其他玩家和好友！

### ISSUE THREAD

**Issue by LUIEE** [wechat-wxapp/wechat-weapp-Game-TNFB#18]
登录、进入配对都没有问题，但是无论是排位赛还是好友配对，都是卡在正在配对，无法配对成功。

**Comment by jacksplwxy** [comment]
此项目仅供参考，相关问题请调试处理

**Comment by LUIEE** [comment]
试过之前其他问题中提出的解决办法(除了“这是因为sortId没有正确传递到服务器上，且ws向服务器发出的信息为matchInfo,但客户端监听的是has_matched”)，用的是修改了server/controllers/tunnel.js的版本，除了注意的两个配置文件，其他的都没有修改。
个人才疏学浅，调试过程v没发现问题，希望您能指条明路。感谢
