### ISSUE TITLE
自己准备了一台centOS服务器应该怎么配置、启动

### ISSUE THREAD

**Issue by DesignerXY** [wechat-wxapp/wechat-weapp-Game-TNFB#22]
你好大牛，如果我自己准备了一台centOS，那应该怎么配置和启动呢？
现在我https已经配置好了，别的还不知道怎么搞，之前没玩过node.js和小程序。

**Comment by jacksplwxy** [comment]
我不是大牛，自行部署没弄过。 您可以参考别人的 [部署](https://github.com/tencentyun/wafer/issues/8)
