### ISSUE TITLE
好友挑战匹配不到人

### ISSUE THREAD

**Issue by flymysql** [wechat-wxapp/wechat-weapp-Game-TNFB#23]
你好，请问发起好友挑战后，好友接收挑战后进入匹配，可是匹配不到人，后台显示信道连接正常。
我用的的是阿里云的服务器，不知道是不是和信道服务器有关系，config.js的配置里我也填了注册的腾讯云appid和secretid,。
不知道这个匹配不到人是为什么，求大佬帮下忙解答一下

**Comment by lvyasen** [comment]
请问一下 其他的服务器也能使用 warfare 么

**Comment by jacksplwxy** [comment]
自行部署文档（ https://github.com/tencentyun/wafer2-startup/wiki/%E8%87%AA%E8%A1%8C%E9%83%A8%E7%BD%B2 ），文档好像没有及时更新，你们可以试试，不行的话就发工单问客服吧

**Comment by northeastsquare** [comment]
我也遇到这个问题，跟踪代码，发现，挑战赛后，客户端通过websocket tunnel, 发出的emit消息，服务端收不到，比如题目类别sortid那个消息，服务端就收不到
