### ISSUE TITLE
排位如何设置机器人与一个人对战答题

### ISSUE THREAD

**Issue by northeastsquare** [wechat-wxapp/wechat-weapp-Game-TNFB#34]
你好，如果只有一个人在线，如何模拟一个用户，与这个人匹配进行对战
如果模拟一个微信用户，还要注册一个，需要手机号，感觉太麻烦；
如果在node服务端，每当一个用户来打排位赛，就模拟一个用户，这样可行吗？大概该怎么弄呢

**Comment by jacksplwxy** [comment]
一定时间内没匹配到其他玩家，你就创建一个机器人与其对战。机器人也很简单，就是当系统出题时，按一定时间内随机选择答案就行了，按随机比例答案的准确率其实也可以控制的，机器人头像名字就从数据库随机取，别取到玩家就行
