### ISSUE TITLE
膜拜帖

### ISSUE THREAD

**Issue by northeastsquare** [wechat-wxapp/wechat-weapp-Game-TNFB#35]
膜拜一下jacksplwxy，客户端和服务端好多消息状态，把这些都能驾驭好，作者好厉害，膜拜

**Comment by jacksplwxy** [comment]
这个其实挺简单的，客户端和服务端定好协议规则，按规则响应就行了。 可能是我当时没啥编程经验，代码写得太烂使得看上去复杂了
