### ISSUE TITLE
客户端emit消息发出，服务端收不到

### ISSUE THREAD

**Issue by northeastsquare** [wechat-wxapp/wechat-weapp-Game-TNFB#37]
首先，客户端登陆到服务端是正常的
出问题的地方是：排位赛，选择比如综合以后，客户端会发出emit消息，并且可以进入success,回调里面，带着sortId, 可是在服务端就是收不到这个消
该怎么办，这个代码库部署，已经部署了一周多了，还没弄好，呜呜

**Comment by jacksplwxy** [comment]
参考这里吧：https://github.com/tencentyun/wafer2-node-sdk
