### ISSUE TITLE
您好，能不能请教下好友对战功能是怎么实现的？

### ISSUE THREAD

**Issue by hhfg** [wechat-wxapp/wechat-weapp-Game-TNFB#42]
您好，能不能请教下好友对战功能是怎么实现的？具体思路..谢谢

**Comment by falseen** [comment]
利用 tunnel（信道） 服务器进行数据交换。可以使用腾讯提供的tunnel，也可以自己搭建，比如这个项目：https://github.com/miwoy/weapp-node-tunnel

不过听说现在腾讯已经关闭了wafer2解决方案，建议你通过微信小程序的云开发功能来实现这个功能。微信官方提供的有示例，开发起来也不难。
