### ISSUE TITLE
如何添加一个单人模式

### ISSUE THREAD

**Issue by 514665587** [wechat-wxapp/wechat-weapp-Game-TNFB#5]

**Comment by jacksplwxy** [comment]
是只有自己答题吗？你答完一题反馈给服务器，服务器再发你一题就行了啊。
现在这个版本只是测试版，写得很乱，后续会更新一版代码优化的，应该就容易读了

**Comment by 514665587** [comment]
我是php程序员,nojs监听的东西不是很懂,tunnel.js 要屏蔽那些东西,才能可以去掉匹配系统直接答题那,向您请教

**Comment by jacksplwxy** [comment]
匹配和答题原理都差不多，关键是明白websocket如何通信的即可。关于可以监听哪些信道事件，建议您参考文档实现自己的业务即可，：https://github.com/tencentyun/wafer/wiki/%E4%BF%A1%E9%81%93%E6%9C%8D%E5%8A%A1
不熟悉JS的话，他们也封装了php的SDK
