### ISSUE TITLE
我有个类似的商业项目

### ISSUE THREAD

**Issue by jillionchen** [wechat-wxapp/wechat-weapp-Game-TNFB#6]
我有个类似的商业项目需求开发，不知道能否合作？

**Comment by saleopt** [comment]
好巧，我也有一个类似的

**Comment by jacksplwxy** [comment]
暂不考虑了

**Comment by jillionchen** [comment]
谢谢




------------------ 原始邮件 ------------------
发件人: "jacksplwxy";<notifications@github.com>;
发送时间: 2018年1月31日(星期三) 上午8:38
收件人: "wechat-wxapp/wechat-weapp-Game-TNFB"<wechat-weapp-Game-TNFB@noreply.github.com>;
抄送: "劲"<80085344@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wechat-wxapp/wechat-weapp-Game-TNFB] 我有个类似的商业项目 (#6)




暂不考虑了
