### ISSUE TITLE
进不了游戏

### ISSUE THREAD

**Issue by DesignerXY** [wechat-wxapp/wechat-weapp-Game-TNFB#7]
您好，首先非常感谢您的分享！
我遇到个问题，多个账号都登录成功，“排位赛”一直显示“对手匹对中…”，“好友对战”一直显示“初始化…”，什么情况呢？还有，怎么快速处理可以单账号也能自己玩的？
谢谢！

**Comment by jacksplwxy** [comment]
后端设置个定时器定时发题就能自己玩。初始化是因为信道只有请求，并没真正打开，具体参考他们文档吧：https://mp.weixin.qq.com/debug/wxadoc/dev/api/network-socket.html
