### ISSUE TITLE
匹配不到人

### ISSUE THREAD

**Issue by Miverk** [wechat-wxapp/wechat-weapp-Game-TNFB#9]
能问下问什么 匹配不到人么 我两个人一起进去的 不能对战

**Comment by L0snight** [comment]
您好 请问您排位界面可以选择答题领域吗  ？  为什么我调试的时候选择不了

**Comment by Miverk** [comment]
我可以选题，你开发环境搭建好了吗？搭建好了环境要把数据库导入到 云数据库中就行了

**Comment by L0snight** [comment]
哦  这样啊  谢谢

**Comment by jacksplwxy** [comment]
更新了一版，您再试下，之前的可能是前端代码没有及时更新过来
